apiVersion: apps/v1
kind: Deployment
metadata:
  name: box-deployment
  labels:
    app: box-app
spec:
  selector:
    matchLabels:
      app: box-app
  replicas: 2
  template:
    metadata:
      labels:
        app: box-app
    spec:
      containers:
        - name: box-app
          image: shuzasa/box-service:v1.0.0
          ports:
            - name: box-service
              containerPort: 8081
          env:
            - name: PORT
              value: ":8081"
            - name: MONGO_HOST
              value: "mongodb:27017"
            - name: APP_VERSION
              value: v1.0.0


---
apiVersion: v1
kind: Service
metadata:
  name: box-service
spec:
  selector:
    app: box-app
  ports:
    - port: 8081
      targetPort: box-service