// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/box.proto

package box

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Box struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Capacity             int32    `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,3,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Available            bool     `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	OwnerId              string   `protobuf:"bytes,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Box) Reset()         { *m = Box{} }
func (m *Box) String() string { return proto.CompactTextString(m) }
func (*Box) ProtoMessage()    {}
func (*Box) Descriptor() ([]byte, []int) {
	return fileDescriptor_78b93522783601a9, []int{0}
}

func (m *Box) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Box.Unmarshal(m, b)
}
func (m *Box) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Box.Marshal(b, m, deterministic)
}
func (m *Box) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Box.Merge(m, src)
}
func (m *Box) XXX_Size() int {
	return xxx_messageInfo_Box.Size(m)
}
func (m *Box) XXX_DiscardUnknown() {
	xxx_messageInfo_Box.DiscardUnknown(m)
}

var xxx_messageInfo_Box proto.InternalMessageInfo

func (m *Box) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Box) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Box) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

func (m *Box) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Box) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func (m *Box) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

type Specification struct {
	Capacity             int32    `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,2,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Specification) Reset()         { *m = Specification{} }
func (m *Specification) String() string { return proto.CompactTextString(m) }
func (*Specification) ProtoMessage()    {}
func (*Specification) Descriptor() ([]byte, []int) {
	return fileDescriptor_78b93522783601a9, []int{1}
}

func (m *Specification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Specification.Unmarshal(m, b)
}
func (m *Specification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Specification.Marshal(b, m, deterministic)
}
func (m *Specification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Specification.Merge(m, src)
}
func (m *Specification) XXX_Size() int {
	return xxx_messageInfo_Specification.Size(m)
}
func (m *Specification) XXX_DiscardUnknown() {
	xxx_messageInfo_Specification.DiscardUnknown(m)
}

var xxx_messageInfo_Specification proto.InternalMessageInfo

func (m *Specification) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Specification) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

type Response struct {
	Box                  *Box     `protobuf:"bytes,1,opt,name=box,proto3" json:"box,omitempty"`
	Boxes                []*Box   `protobuf:"bytes,2,rep,name=boxes,proto3" json:"boxes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_78b93522783601a9, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetBox() *Box {
	if m != nil {
		return m.Box
	}
	return nil
}

func (m *Response) GetBoxes() []*Box {
	if m != nil {
		return m.Boxes
	}
	return nil
}

func init() {
	proto.RegisterType((*Box)(nil), "box.Box")
	proto.RegisterType((*Specification)(nil), "box.Specification")
	proto.RegisterType((*Response)(nil), "box.Response")
}

func init() { proto.RegisterFile("proto/box.proto", fileDescriptor_78b93522783601a9) }

var fileDescriptor_78b93522783601a9 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x41, 0x4b, 0xfb, 0x50,
	0x0c, 0xc0, 0xff, 0xaf, 0xdd, 0xf6, 0xef, 0x22, 0x53, 0xc9, 0xe9, 0x59, 0x54, 0x4a, 0x4f, 0x3d,
	0x4d, 0x98, 0x07, 0xcf, 0x16, 0x1c, 0xe8, 0xb1, 0x3b, 0x78, 0x1c, 0xaf, 0xed, 0x53, 0x03, 0x6b,
	0x53, 0xda, 0xb2, 0x3d, 0x3f, 0x8c, 0xdf, 0x55, 0x1a, 0x99, 0x52, 0x0f, 0xde, 0x92, 0x5f, 0x48,
	0xf8, 0x25, 0x81, 0xb3, 0xa6, 0xe5, 0x9e, 0x6f, 0x72, 0x76, 0x4b, 0x89, 0xd0, 0xcf, 0xd9, 0xc5,
	0x1f, 0x0a, 0xfc, 0x94, 0x1d, 0x9e, 0x82, 0x47, 0xa5, 0x56, 0x91, 0x4a, 0xe6, 0x99, 0x47, 0x25,
	0x86, 0x10, 0x14, 0xa6, 0x31, 0x05, 0xf5, 0xef, 0xda, 0x8b, 0x54, 0x32, 0xcd, 0xbe, 0x73, 0xbc,
	0x02, 0xa8, 0x8c, 0xdb, 0x1e, 0x2c, 0xbd, 0xbe, 0xf5, 0xda, 0x97, 0xea, 0xbc, 0x32, 0xee, 0x59,
	0x00, 0x22, 0x4c, 0x6a, 0x53, 0x59, 0x3d, 0x91, 0x61, 0x12, 0xe3, 0x25, 0xcc, 0xcd, 0xde, 0xd0,
	0xce, 0xe4, 0x3b, 0xab, 0xa7, 0x91, 0x4a, 0x82, 0xec, 0x07, 0xe0, 0x05, 0x04, 0x7c, 0xa8, 0x6d,
	0xbb, 0xa5, 0x52, 0xcf, 0xa4, 0xeb, 0xbf, 0xe4, 0x8f, 0x65, 0xfc, 0x04, 0x8b, 0x4d, 0x63, 0x0b,
	0x7a, 0xa1, 0xc2, 0xf4, 0xc4, 0xf5, 0x48, 0x4c, 0xfd, 0x29, 0xe6, 0xfd, 0x12, 0x8b, 0xd7, 0x10,
	0x64, 0xb6, 0x6b, 0xb8, 0xee, 0x2c, 0x86, 0x30, 0xac, 0x2f, 0x13, 0x4e, 0x56, 0xc1, 0x72, 0xb8,
	0x4a, 0xca, 0x2e, 0x1b, 0x20, 0x5e, 0xc3, 0x34, 0x67, 0x67, 0x3b, 0xed, 0x45, 0xfe, 0xa8, 0xfa,
	0x85, 0x57, 0x0f, 0x00, 0x29, 0xbb, 0x8d, 0x6d, 0xf7, 0x54, 0x58, 0xbc, 0x83, 0xf3, 0x35, 0xd5,
	0xe5, 0xfd, 0x71, 0x9b, 0xe1, 0x9a, 0x28, 0x2d, 0x23, 0xf1, 0x70, 0x21, 0xec, 0x28, 0x10, 0xff,
	0xcb, 0x67, 0xf2, 0x86, 0xdb, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x38, 0x2f, 0xaa, 0x3c, 0x99,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BoxServiceClient is the client API for BoxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BoxServiceClient interface {
	FindAvailableBox(ctx context.Context, in *Specification, opts ...grpc.CallOption) (*Response, error)
}

type boxServiceClient struct {
	cc *grpc.ClientConn
}

func NewBoxServiceClient(cc *grpc.ClientConn) BoxServiceClient {
	return &boxServiceClient{cc}
}

func (c *boxServiceClient) FindAvailableBox(ctx context.Context, in *Specification, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/box.BoxService/FindAvailableBox", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BoxServiceServer is the server API for BoxService service.
type BoxServiceServer interface {
	FindAvailableBox(context.Context, *Specification) (*Response, error)
}

// UnimplementedBoxServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBoxServiceServer struct {
}

func (*UnimplementedBoxServiceServer) FindAvailableBox(ctx context.Context, req *Specification) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAvailableBox not implemented")
}

func RegisterBoxServiceServer(s *grpc.Server, srv BoxServiceServer) {
	s.RegisterService(&_BoxService_serviceDesc, srv)
}

func _BoxService_FindAvailableBox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Specification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxServiceServer).FindAvailableBox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/box.BoxService/FindAvailableBox",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxServiceServer).FindAvailableBox(ctx, req.(*Specification))
	}
	return interceptor(ctx, in, info, handler)
}

var _BoxService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "box.BoxService",
	HandlerType: (*BoxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAvailableBox",
			Handler:    _BoxService_FindAvailableBox_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/box.proto",
}
